
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/TestGtihupActions/TestGtihupActions/TestGtihupActions.API/bin/Release/net7.0/publish/
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: FTP Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          port: ${{ secrets.FTP_PORT }}
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /TestApiForActions/
