# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Settlement Web Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: linchpin/action-build-yarn-npm@master
     
    - run: yarn --cwd  "/home/runner/work/TestGtihupActions/TestGtihupActions/testgtihupactions.webapplication" build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 40.113.58.136
        username: gridboxuser
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /TestVueForActions/
        protocol : ftps
        local-dir : ./TestGtihupActions/testgtihupactions.webapplication/dist/
