# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Settlement Web Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Run install
      uses: borales/actions-yarn@v4
        
    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
       cmd: build:prod yarn --cwd "/home/runner/work/TestGtihupActions/TestGtihupActions/testgtihupactions.webapplication" build 
   
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 40.113.58.136
        username: gridboxuser
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /TestVueForActions/
        protocol : ftps
        local-dir : ./testgtihupactions.webapplication/dist/
